[package]
name = "lab1_2023CS10204_2023CS10076_2023CS10186"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "lab1_2023CS10204_2023CS10076_2023CS10186"     # Your CLI binary name
path = "src/bin/main.rs"

[dependencies]
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["Window", "Document", "Element", "HtmlElement"] }